spring.application.name=MyDiaryRestAPI

spring.jpa.database= mysql

spring.datasource.url= jdbc:mysql://localhost/mydiaryapp
spring.datasource.username= root
spring.datasource.password= nagumca123

spring.jpa.show-sql= true

server.servlet.context-path= /mydiaryrestapi